<?php
namespace app\shop\controller;
use think\Session;
class Home extends Base{

    /**
     *   引用Base _initialize 验证权限
     */
    public function _initialize(){
        /*Permission_verification 父级的权限验证方法*/
        parent::Permission_verification(); // TODO: Change the autogenerated stub
    }

    /**
     *  index 显示login主页
     */
    public function index(){
        if(Session::has('admin_id')) {
            /*当前用户已经登录*/
            return $this->fetch("home/index");
        }else return $this->fetch("login/index");
    }

    /**
     * 返回上一层
     */
    public function ReturnUp(){
        return '<script> history.go(-2); </script>';
    }

    /**
     * 返回上一层
     */
    public function ReturnOne(){
        return '<script> history.go(-1); </script>';
    }
}