<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/5/7 0007
 * Time: 9:37
 */
namespace app\BlogAdmin\controller;
use \think\Db;
use think\Session;
use \think\View;
use \think\Request;
session_start();
class Auth extends Base{
    /*调用Base*/
    public function _initialize()
    {
        parent::check(); // TODO: Change the autogenerated stub
    }
    public function home(){
        echo $this->fetch("admin/auth");
    }

}