<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/24 0024
 * Time: 16:15
 */
namespace app\BlogAdmin\controller;
use \think\Controller as Con;
use \think\Db;
use think\Session;
use \think\View;
use \think\Request;
use \think\paginator;
use \app\blogadmin\controller\Base as Base;
use \app\BlogAdmin\model\admin as AdminModel;
use \app\BlogAdmin\model\article as ArticleModel;
use \app\BlogAdmin\model\category as CategoryModel;
class  Article extends Base{

    /*调用Base*/
    public function _initialize()
    {
        parent::check(); // TODO: Change the autogenerated stub
    }

    /**
     *  showList() 显示List()
     */
    public function showList(){
        if (Session::has('admin_id')) {
            $ArticleModel = new ArticleModel();
            $page = Request::instance()->get('page');
            $page = isset($page)?($page-1)*5:0;
            $ArticleDate = $ArticleModel->limit($page,5)->select();
            $page = $ArticleModel->paginate(5);
            $this->assign([
                'ArticleDate' => $ArticleDate,
                'page' => $page,
            ]);
            $this->CategoryDate();
            return $this->fetch('list');
        }else  return $this->fetch('admin/Login');
    }
    /**
     *  searchArticle() 文章搜索
     */
    public function searchArticle(){
        $Request=Request::instance();
        if($Request->has('SearchBtn')) {
            $Type = $Request->post('Type');  //标题
            $State = $Request->post('State');  //状态
            $Text = $Request->post('Text');  //内容
            if ($Type === "按标题") {
                /*选择标题搜索*/
                $this->Title($Text);
                $this->CategoryDate();
            } else if ($Type === "按发布人") {
                /*选择发布人搜索*/
                $this->Author($Text);
                $this->CategoryDate();
            } else if ($Type === "按所属类") {
                /*选择所属类搜索*/
                $this->Clas($Text);
                $this->CategoryDate();
            }
            if($State=== "已审核"){
                $ArticleModel = new ArticleModel();
                $page = Request::instance()->get('page');
                $page = isset($page)?($page-1)*5:0;
                $ArticleDate = $ArticleModel->where(['article_state'=>1])->limit($page,5)->select();
                $page = $ArticleModel->paginate(5);
                $this->assign([
                    'ArticleDate' => $ArticleDate,
                    'page' => $page,
                ]);
            }else if($State=== "未审核") {
                $ArticleModel = new ArticleModel();
                $page = Request::instance()->get('page');
                $page = isset($page)?($page-1)*5:0;
                $ArticleDate = $ArticleModel->limit($page,5)->where(['article_state'=>-1])->select();
                $page = $ArticleModel->paginate(5);
                $this->assign([
                    'ArticleDate' => $ArticleDate,
                    'page' => $page,
                ]);
            }
            return $this->fetch('list');
        }
    }
    //搜索方法
    public function Title($Text){
        $Length = Request::instance()->get('length');
        $Page = Request::instance()->get('page');
        $ArticleModel = new ArticleModel();
        $page = isset($Page)?($Page-1)*$Length:0;
        $lenght = isset($Length) ? $Length : 5;
        $ArticleDate = $ArticleModel->limit($page,$lenght)->select();
        $trpage = $ArticleModel->paginate($Length);
        $this->assign([
            'ArticleDate' => $ArticleDate,
            'page' => $trpage,
            'Length' => $Length,
            'pageIng' => $Page,
        ]);
        $this->CategoryDate();
        return  $this->fetch('return');

    }
    //作者
    public function Author($Text){
        $ArticleModel=new ArticleModel(); 
//        $page = Request::instance()->get('page');
//        $page = isset($page)?($page-1)*5:0;
        $ArticleDate=$ArticleModel->where("user_name like '%$Text%'")->select();
//        $page = $ArticleModel->paginate(5);
        $this->assign([
            'ArticleDate'=>$ArticleDate,
            'page' => '',
        ]);
    }
    //所属类
    public function Clas($Text){
        $ArticleModel=new ArticleModel();
        $ArticleDate=Db::query("select * from  tb_category,tb_article where tb_category.category_id=tb_article.category_id and tb_category.category_name like '%$Text%'");
        $this->assign([
            'ArticleDate'=>$ArticleDate,
        ]);
    }
    // CategoryDate
    public function CategoryDate(){
        $CategoryModel=new CategoryModel();
        $CategoryDate=$CategoryModel->where('father_id!=0')->select();
        $this->assign([
            'CategoryDate'=>$CategoryDate,
        ]);
        $CategoryModel=new CategoryModel();
        $FatherDate=$CategoryModel->where('father_id=0 ')->select();
        $this->assign([
            'FatherDate'=>$FatherDate,
        ]);
    }

    /**
     * updateArticle() 文章修改
     */
    public function updateArticle(){
        /*标头信息*/
        $this->assign([
            'Header'=>'修改文章',
        ]);
        $Request=Request::instance();
        $Article_id=$Request->get('Article_id');
        /*文章信息*/
        $ArticleModel=new ArticleModel();
        $ArticleDate=$ArticleModel->where(['Article_id'=>$Article_id])->select();
        $this->assign([
            'ArticleDate'=> $ArticleDate,
        ]);
        $this->CategoryDate();
        return $this->fetch('details');
    }

    /**
     * 文章删除
     */
    public function deleteArticle(){
        $Request=Request::instance();
        $Article_id=$Request->get('Article_id');
        $ArticleModel=new ArticleModel();
        $Returun=$ArticleModel->where(['Article_id'=>$Article_id])->delete();
        if($Returun>-1){
//            echo '<script> alert(" 删除成功!");</script>';
//            return '<script> window.location.href="/index.php/blogadmin/article/showList" </script>';
            return header('location: '.$_SERVER['HTTP_REFERER']);
        }
    }

    /**
     * 文章修改
     */
    public function uodateArticle()
    {
        if (Session::has('admin_id')) {
            /*存在admin 已经登录*/
            $Request = Request::instance();
            $select = $Request->post('select');  //所属类别id
            $title = $Request->post('title');  // 文章标头
            $textarea = $Request->post('textarea');  //文章内容
//            $user_name = $Request->post('user_name');  //作者
            $article_id= $Request->post('article_id'); //文章id
            $article_love=$Request->post('article_love'); //收藏数量
            if($title && $textarea && $article_love) {
                /*创建date数据接收*/
                $Date = array(
                    'category_id' => $select,
                    'article_title' => $title,
                    'article_content' => $textarea,
                    'article_love' => $article_love,
                    'article_time' => date("Y-m-d H:i:s"),  //当前时间
                );
                $ArticleModel = new ArticleModel;
                $Retuen = $ArticleModel->where(['article_id' => $article_id])->update($Date);
                if ($Retuen > -1) {
                    return '<script> alert("文章更新成功!");window.location.href="../Article/showList" </script>';
//                return header('location: '.$_SERVER['HTTP_REFERER']);
//                 return  '<script>history.go(-2); </script>';
                }
            }else    return '<script> alert("输入项不能为null!");history.go(-1); </script>';
        }else  return $this->fetch('Login');
    }

    /**
     *  文章添加 显示
     */
    public function insertArticle(){
        /*标头信息*/
        $this->assign([
            'Header'=>'添加文章',
        ]);
        $this->CategoryDate();
        return $this->fetch('insert');
    }

    /**
     * 文章添加
     */
    public  function insert(){
        if (Session::has('admin_id')) {
            /*存在admin 已经登录*/
            $Request = Request::instance();
            $select = $Request->post('select');  //所属类别id
            $title = $Request->post('title');  // 文章标头
            $state = $Request->post('state');  // 文章状态
            $textarea = $Request->post('textarea');  //文章内容
            $user_id=Session::get('admin_id');  //作者id
            $AdminModel = new AdminModel();
            $AdminDate = $AdminModel->where(['admin_id'=>$user_id])->select();
            $user_name=$AdminDate[0]['admin_name'];  //作者name
            $article_time = date("Y-m-d H:i:s"); // 发布时间

            if($title && $textarea) {
                if ($state === "打开") {
                    $state = -1;
                    $Date = array(
                        'category_id' => $select,
                        'article_title' => $title,
                        'article_content' => $textarea,
                        'article_time' => $article_time,
                        'user_id' => $user_id,
                        'user_name' => $user_name,
                        'article_state' => $state,
                    );
                    $ArticleModel = new ArticleModel;
                    $Retuen = $ArticleModel->insert($Date);
                    if ($Retuen > -1) {
                        return '<script> alert("文章审核中!");window.location.href="../Article/showList" </script>';
                    }
                } else {
                    $state = 1;
                    $Date = array(
                        'category_id' => $select,
                        'article_title' => $title,
                        'article_content' => $textarea,
                        'article_time' => $article_time,
                        'user_id' => $user_id,
                        'user_name' => $user_name,
                        'article_state' => $state,
                    );
                    $ArticleModel = new ArticleModel;
                    $Retuen = $ArticleModel->insert($Date);
                    if ($Retuen > -1) {
                        return '<script> alert("文章发布成功!");window.location.href="../Article/showList" </script>';
                    }
                }
            }else    return '<script> alert("输入项不能为null!");history.go(-1); </script>';
        }else  return $this->fetch('Login');
    }

    /**
     *  文章审核
     */
    public function examineArticle(){
        if (Session::has('admin_id')) {
            $ArticleModel = new ArticleModel();
            $page = Request::instance()->get('page');
            $page = isset($page)?($page-1)*5:0;
            $ArticleDate = $ArticleModel->limit($page,5)->where(['article_state'=>-1])->select();
            $page = $ArticleModel->paginate(count($ArticleDate)-count($ArticleDate)-1);
            $this->assign([
                'ArticleDate' => $ArticleDate,
                'page' => $page,
            ]);
            $this->CategoryDate();
            return $this->fetch('examine');
        }else  return $this->fetch('admin/Login');
    }

    /**
     *  列表状态
     */
    public function updateListState(){
        $Request = Request::instance();
        if($Request->has('id') && $Request->has('state')){
            $ArticleModel=new ArticleModel();
            $article_id=$Request->get('id');
            $article_state = $Request->get('state');
            if($article_state==1)
                $article_state=-1;
            else  if($article_state==-1)
                $article_state=1;
            $retuen = $ArticleModel->where(['article_id'=>$article_id])->update(['article_state'=>$article_state]);
            if($retuen>-1){
//                return header('location: '.$_SERVER['HTTP_REFERER']);
                return '<script> alert("状态修改成功!");window.location.href="../Article/showList" </script>';
            }
        }
    }

    /**
    *  审核状态
    */
    public function updateExamineState(){
        $Request = Request::instance();
        if($Request->has('id') && $Request->has('state')){
            $ArticleModel=new ArticleModel();
            $article_id=$Request->get('id');
            $article_state = $Request->get('state');
            if($article_state==1)
                $article_state=-1;
            else  if($article_state==-1)
                $article_state=1;
            $retuen = $ArticleModel->where(['article_id'=>$article_id])->update(['article_state'=>$article_state]);
            if($retuen>-1){
                return '<script> alert("状态修改成功!");window.location.href="../Article/examineArticle" </script>';
            }
        }
    }

    /*改变显示数量*/
    public function dataTablesExampleLength(){
        $Length = Request::instance()->get('length');
        $Page = Request::instance()->get('page');
        $ArticleModel = new ArticleModel();
        $page = isset($Page)?($Page-1)*$Length:0;
        $ArticleDate = $ArticleModel->limit($page,$Length)->select();
        $trpage = $ArticleModel->paginate($Length);
        $this->assign([
            'ArticleDate' => $ArticleDate,
            'page' => $trpage,
            'Length' => $Length,
            'pageIng' => $Page,
        ]);
        $this->CategoryDate();
        echo  $this->fetch('return');
    }

    /* AJAX  搜索*/
    public function searchAJSX(){
        $Nmae = Request::instance()->get('name');  //搜索输入值
        $Type = Request::instance()->get('type');  //搜索类型
        $Length = Request::instance()->get('length');  //显示的长度

//        $Page = Request::instance()->get('page');
        $ArticleModel = new ArticleModel();
//        $page = isset($Page)?($Page-1)*$Length:0;
        if($Type==="按标题") {
            $ArticleDate = $ArticleModel
//                ->limit(0, 5)
                ->where("article_title like '%$Nmae%'")
                ->select();
        }else if($Type==="按所属类"){
            $ArticleDate = $ArticleModel
//                ->limit(0, 5)
                ->where("article_title like '%$Nmae%'")
                ->select();
        }else if($Type==="按发布人"){
            $ArticleDate = $ArticleModel
//                ->limit(0, 5)
                ->where("user_name like '%$Nmae%'")
                ->select();
        }
        $this->assign([
            'ArticleDate' => $ArticleDate,
            'page' => 0,
            'Length' => 5,
            'pageIng' => 0,
        ]);
        $this->CategoryDate();
        echo  $this->fetch('return');
    }
    /* AJAX 状态搜索*/
    public function stateAJAX(){
        $State= Request::instance()->get('state');  //状态
        $Length = Request::instance()->get('length');  // 长度
        $Page = Request::instance()->get('page'); // 页
        $page = isset($Page)?($Page-1)*$Length:0;
        $ArticleModel = new ArticleModel();
        $trpage = $ArticleModel->paginate($Length);
//        $page = isset($Page)?($Page-1)*$Length:0;
        if($State==="已审核") {
            $ArticleDate = $ArticleModel
//                ->limit($page,$Length)
                ->where("article_state =1")
                ->select();
        }else  if($State==="未审核") {
            $ArticleDate = $ArticleModel
//                ->limit($page,$Length)
                ->where("article_state =-1")
                ->select();
        }
        $this->assign([
            'ArticleDate' => $ArticleDate,
            'page' => 0,
            'Length' => 5,
            'pageIng' => 0,
        ]);
        $this->CategoryDate();
        echo  $this->fetch('return');
    }
}